tab:
  animated: false

  header:
    - ""
    - "<yellow><bold>TestServer</bold></yellow>"
    - "<gray>Playing on <gold>S1</gold></gray>"
    - ""

  footer:
    - ""
    - "<yellow>{online}</yellow> <gray>players playing</gray>"
    - "<gold>Server.minehut.gg</gold>"
    - ""