name: GPlugin
version: 1.0
main: me.wxterfall.gplugin.GPlugin
api-version: '1.20'
author: wxterfall

commands:
  fly:
    description: Toggles flight
    usage: /fly
    aliases: [f, flight]
    permission: fly
    permission-message: "GPlugin - You do not have permission!"

  discord:
    description: Join the discord
    usage: /discord
    aliases: [d]

  vanish:
    description: Go invisible
    usage: /vanish [player]
    aliases: [v]
    permission: staff.vanish
    permission-message: "GPlugin - You do not have permission!"

  staffchat:
    description: Toggle staff chat or sends a message in staff chat
    usage: /staffchat [message]
    aliases: [sc]
    permission: staff.staffchat
    permission-message: "GPlugin - You do not have permission!"

  freeze:
    description: Freeze/unfreeze a player
    usage: /freeze [player]
    aliases: [fr]
    permission: staff.freeze
    permission-message: "GPlugin - You do not have permission!"

  ranks:
    description: Opens the rank manager menu
    usage: /ranks <player>
    permission: staff.ranks
    permission-message: "GPlugin - You do not have permission!"